# Generated by Django 5.1 on 2025-03-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
