# Generated by Django 5.1 on 2025-03-15 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='worded_from_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='worded_to_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
