# Generated by Django 5.1 on 2025-03-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_riderequest_worded_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='worded_from_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='worded_to_location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
