# Generated by Django 5.1 on 2025-03-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_riderequest_worded_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='zone',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
