# Generated by Django 5.1 on 2025-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_riderequest_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
