# Generated by Django 5.1.1 on 2025-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_token_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokens',
            field=models.IntegerField(null=True),
        ),
    ]
